[build]
  base = "."
  publish = "dist/public"
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[build.environment]
  NODE_VERSION = "20"

# Proxy para chamadas OPTIONS (preflight CORS) - precisa vir primeiro
[[redirects]]
  from = "/api/*"
  to = "https://api-clinica-psicologia.onrender.com/api/:splat"
  status = 200
  force = true
  method = "OPTIONS"
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization", Access-Control-Allow-Credentials = "true"}

# Proxy para todas as outras chamadas API (GET, POST, etc.)
[[redirects]]
  from = "/api/*"
  to = "https://api-clinica-psicologia.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization", Access-Control-Allow-Credentials = "true"}

# Página principal - este redirecionamento deve ser o último
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"