[build]
  base = "."
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://sua-api-backend.com/api/:splat"
  status = 200
  force = true